import { PublicKey, type Connection } from "@solana/web3.js";
import { AnchorProvider, Program, type Idl, type Wallet } from "@coral-xyz/anchor";
import { PROGRAM_ID } from "./solana";

/**
 * Centralized Anchor client + PDA derivations for the zkHelios program.
 *
 * The real IDL is generated by the Anchor program in Session 6 and will be
 * dropped into `packages/idl`. Until then we use a minimal placeholder IDL so
 * the client wiring + PDA helpers are ready for Session 4's proof flow.
 */

export const MOCK_IDL: Idl = {
  address: PROGRAM_ID.toBase58(),
  metadata: { name: "zkhelios", version: "0.1.0", spec: "0.1.0" },
  instructions: [],
  accounts: [],
  events: [],
  errors: [
    { code: 6000, name: "programPaused", msg: "Program is paused" },
    { code: 6001, name: "circuitNotFound", msg: "Circuit not found" },
    { code: 6002, name: "circuitDisabled", msg: "Circuit is disabled" },
    { code: 6003, name: "invalidPublicInputCount", msg: "Invalid public input count" },
    { code: 6004, name: "invalidProofFormat", msg: "Invalid proof format" },
    { code: 6005, name: "proofVerificationFailed", msg: "Proof verification failed" },
    { code: 6006, name: "insufficientFunds", msg: "Insufficient funds" },
    { code: 6007, name: "unauthorized", msg: "Unauthorized" },
    { code: 6010, name: "nonceAlreadyUsed", msg: "Nonce already used" },
    { code: 6012, name: "proofAlreadyExists", msg: "Proof already exists" },
  ],
};

/** Map of on-chain custom error codes → human-readable messages. */
export const PROGRAM_ERRORS: Record<number, string> = Object.fromEntries(
  (MOCK_IDL.errors ?? []).map((e) => [e.code, e.msg ?? e.name]),
);

/**
 * Build a typed Program instance from a connection + wallet.
 * Lazily constructed; Session 4 uses this for `verify_proof` calls.
 */
export function getProgram(connection: Connection, wallet: Wallet): Program {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  return new Program(MOCK_IDL, provider);
}

// ── PDA derivations (seeds must match the Anchor program, Session 6) ──────────

const enc = (s: string) => Buffer.from(s, "utf8");

/** VerifierConfig singleton — seeds: ["verifier_config"]. */
export function findVerifierConfigPDA(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([enc("verifier_config")], PROGRAM_ID);
}

/** UserAccount — seeds: ["user", authority]. */
export function findUserAccountPDA(authority: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([enc("user"), authority.toBuffer()], PROGRAM_ID);
}

/** CircuitRegistry — seeds: ["circuit", circuit_id as u32 LE]. */
export function findCircuitPDA(circuitId: number): [PublicKey, number] {
  const buf = Buffer.alloc(4);
  buf.writeUInt32LE(circuitId, 0);
  return PublicKey.findProgramAddressSync([enc("circuit"), buf], PROGRAM_ID);
}

/** ProofAccount — seeds: ["proof", authority, nonce as u64 LE]. */
export function findProofAccountPDA(authority: PublicKey, nonce: bigint): [PublicKey, number] {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(nonce, 0);
  return PublicKey.findProgramAddressSync([enc("proof"), authority.toBuffer(), buf], PROGRAM_ID);
}
